name: webcam-app
version: "1.0"
summary: Webcam app for snappy ubuntu core
description: Exposes your webcam and access using a Ubuntu phone app called "webcamapp"
confinement: strict

apps:
  webcam:
    command: bin/webcamserv
    daemon: simple
    plugs: [camera,network,network-bind]
  sh:
    command: bin/sh

parts:
  cam:
    plugin: go
    source: https://github.com/liu-xiao-guo/webcamserv
    source-type: git
    stage-packages:
      - fswebcam
    filesets:
      fswebcam:
        - usr/bin/fswebcam
        - lib
        - usr/lib
      go-server:
        - bin/webcam*
    snap:
        - $fswebcam
        - $go-server
  glue:
    plugin: copy
    files:
      webcam: bin/webcam
      capture: bin/capture
      ./bin/sh: bin/sh
      
